apiVersion: v1
kind: Service
metadata:
  name: kube-client-service
spec:
  selector:
    app: kube-client
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-client
spec:
  selector:
    matchLabels:
      app: kube-client
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-client
    spec:
      containers:
      - name: kube-client
        image: docker.io/levyn96/pod-by-ip:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
